apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlbinL/ocp_test'
    targetRevision: main
    path: deploy
  destination:
    server: default/api-crc-testing:6443
    namespace: argocd
  syncPolicy:
    createNamespace: true
    automated:
      prune: true
      selfHeal: true
