apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-project
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'git@github.com:AlbinL/private-project'
    targetRevision: main
    path: ./
  destination:
    server: https://api.crc.testing:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
