apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/AlbinL/argocd
    path: argo-projects
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://api.crc.testing:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
