apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/AlbinL/argo-projects'
    targetRevision: main
    path: argocd
  destination:
    server: https://api.crc.testing:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
